#!/usr/bin/env zsh

if [ -d /snap/bin/ ]
then
  PATH=${PATH}:/snap/bin/
fi

if [ -d ${HOME}/.extbin ]
then
  PATH=${PATH}:${HOME}/.extbin
fi

if [ -d ${HOME}/.bin ]
then
  PATH=${PATH}:${HOME}/.bin
fi
