#!/usr/bin/env zsh

export PYENV_ROOT="${HOME}/.gitrepos/github.com/pyenv/pyenv"
export PYENV_GLOBAL_VERSION=${PYENV_ROOT}/version
export PATH="${PYENV_ROOT}/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init -)"
fi
