#!/usr/bin/env zsh

export JENV_ROOT="${HOME}/.gitrepos/github.com/jenv/jenv"
export JENV_GLOBAL_VERSION=${JENV_ROOT}/version
export PATH="${JENV_ROOT}/bin:$PATH"

if command -v jenv 1>/dev/null 2>&1
then
  eval "$(jenv init -)"
fi
