#!/usr/bin/env zsh

export RBENV_ROOT="${HOME}/.rbenv"
export RBENV_GLOBAL_VERSION=${RBENV_ROOT}/version
export PATH="${RBENV_ROOT}/bin:$PATH"

if command -v rbenv 1>/dev/null 2>&1
then
  eval "$(rbenv init -)"
fi
