#!/usr/bin/env zsh

export NODENV_ROOT="${HOME}/.nodenv"
export NODENV_GLOBAL_VERSION=${NODENV_ROOT}/version
export PATH="${NODENV_ROOT}/bin:$PATH"

if command -v nodenv 1>/dev/null 2>&1
then
  eval "$(nodenv init -)"
fi
