# Set tmux to 256 colors
# https://sota1235.hatenablog.com/entry/2015/07/09/203000
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# key bind, C-b |, C-v -
# https://qiita.com/zwirky/items/adbf22abad7d7822456b
bind | split-window -h
bind - split-window -v

# Set up status line
# https://qiita.com/nojima/items/9bc576c922da3604a72b
set-option -g status-interval 1
set-option -g status-justify "centre"
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"
set-option -g status-left-length 100
set-option -g status-right-length 100

# Set status line position top
# https://qastack.jp/unix/15316/how-can-i-move-tmuxs-status-bar-to-the-top
set-option -g status-position top

set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#I: #W"

set-option -g status-left  "    #S:#I.#P   #(whoami)  ﲾ #h   #(~/.bin/tmux_ssid)  #(~/.bin/tmux_lip)  龍#(tmux_netbps)mbps "

set-option -g status-right "   #(tmux_uptime)   #(tmux_cpu_mhz)mhz   #(tmux_mem_usage)% FREE   %Y/%m/%d(%a)   %H:%M:%S "

# mouse mode on
# https://github.com/NHDaly/tmux-better-mouse-mode
set-option -g mouse on

# Tmux Plugin Manager
# https://github.com/tmux-plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-tmux-battery'
set -g @plugin 'tmux-plugins/tmux-online=status'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# better-mouse-mode
# https://github.com/NHDaly/tmux-better-mouse-mode
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

run '~/.tmux/plugins/tpm/tpm'
