#!/usr/bin/env zsh

mem() {
  local command="free -${1} | grep Mem | sed -e 's/ \+/ /g' | cut -d ' ' -f ${2}"
  eval ${command}
}
mem_total() {
  mem $1 2
}

mem_used() {
  mem $1 3
}

mem_free() {
  mem $1 4
}

mem_free_percentage() {
  local free_mem=`mem_free b`
  local total_mem=`mem_total b`
  echo $(( ${free_mem} * 100 / ${total_mem} ))
}

disk() {
  local command="df -${1} / | tail -n 1 | sed -e 's/ \+/ /g' | cut -d ' ' -f ${2}"
  eval ${command}
}

disk_total() {
  disk ${1} 2
}

disk_used() {
  disk ${1} 3
}

disk_free() {
  disk ${1} 4
}

cpu() {
  local command="vmstat | tail -n 1 | sed -e 's/ \+/ /g' | cut -d ' ' -f ${1}"
  eval ${command}
}

cpu_user() {
  cpu 14
}

cpu_system() {
  cpu 15
}

cpu_idle() {
  cpu 16
}

cpu_wait() {
  cpu 17
}

cpu_other() {
  cpu 18
}

cpu_usage() {
  echo "U:`cpu_user` S:`cpu_system` I:`cpu_idle` W:`cpu_wait` O:`cpu_other`" 
}

sys_cpu_pcorenum() {
  cat /proc/cpuinfo | grep "cpu cores" | uniq | cut -d ':' -f 2 | sed 's/ //g'
}

sys_cpu_lcorenum() {
  cat /proc/cpuinfo | grep processor | wc -l
}

sys_cpu_model() {
  cat /proc/cpuinfo | grep "model name" | uniq | cut -d ":" -f 2 | sed 's/^[ \t]*//'
}

sys_cpu_average_mhz() {
  cat /proc/cpuinfo | grep "cpu MHz" | cut -d ':' -f 2 | awk '{sum+=$1} END {print sum/NR}' | cut -d '.' -f 1
}

sys_wifi_ssid() {
  iwgetid -r
}

sys_net_ipaddress() {
  hostname -I
}

sys_net_bps() {
  nmcli dev wifi | grep `sys_wifi_ssid` | head -n 1 | sed 's/ \+/ /g' | cut -d ' ' -f 6
}

sys_net_wave_graph() {
  nmcli dev wifi | grep `sys_wifi_ssid` | head -n 1 | sed 's/ \+/ /g' | cut -d ' ' -f 9
}

sys_net_wave_fig() {
  nmcli dev wifi | grep `sys_wifi_ssid` | head -n 1 | sed 's/ \+/ /g' | cut -d ' ' -f 8
}

sys_net_wave_level() {
  local level=`sys_net_wave_fig`
  local lvlctr=`expr ${level} / 10`
  local lvlblank=`expr 10 - ${lvlctr}`

  local lvlstr=""
  for i in `seq 1 ${lvlctr}`
  do
    lvlstr="${lvlstr}■"
  done
  for i in `seq 1 ${lvlblank}`
  do
    lvlstr="${lvlstr}□"
  done
  echo "${lvlstr} ${level}"
}

is_git_repo() {
  git rev-parse --is-inside-work-tree > /dev/null 2>&1
  echo $?
}

sys_os_desc() {
  cat /etc/lsb-release | grep DISTRIB_DESCRIPTION | cut -d '=' -f 2 | sed 's/"//g'
}

git_cbranch() {
  git rev-parse --abbrev-ref HEAD
}

git_stash_size() {
  git stash list | wc -l
}
