#!/bin/bash

function splash () {
  echo "################################################################################"
  if [ -z ${TMUX} ]
  then
    toilet -f ivrit ${SHELL}
    bash --version | head -n 1
  else
    toilet -f ivrit 'TMUX'
    tmux -V
  fi
  echo "################################################################################"
}
