#!/usr/bin/env zsh
source ${HOME}/.lib/cpuinfo

cpuInfo() {
  local vendor=`getCPUVendor`
  local processors=`getCPUProcessorCount`
  local cores=`getCPUCoreCount`
  local averageClock=`getCPUAverageMHZ`

  echo "\uf1ad ${vendor} \uf2db ${cores} \ue28c ${processors} \uf651 ${averageClock}MHZ"
}

cpuInfo
