#!/usr/bin/env zsh
source ${HOME}/.lib/netinfo

etherStatus() {
  local etherStatus=`getEtherStatus`
  if [ "${etherStatus}" = "connected" ]
  then
    echo "\uf700`getEtherConnection` \uf502 `getEtherIpAddress`"
  else
    echo "\uf701"
  fi
}

etherStatus
