#!/usr/bin/env zsh
source ${HOME}/.lib/netinfo

etherStatus() {
  local etherStatus=`getEtherStatus`
  if [ "${etherStatus}" = "connected" ]
  then
    echo "\uf700 `getEtherConnection` \uf502 `getEtherIpAddress` \uf9c4`getEtherBitRate`"
  else
    echo "\uf701 NO ETHER"
  fi
}

etherStatus
