#!/usr/bin/env zsh

source ${HOME}/.zshrc_func/800_myfuncs
source ${HOME}/.zshrc_func/100_logging

gitc() {
  local user=${1}
  local repository=${2}
  git clone https://github.com/${user}/${repository}.git ${HOME}/.gitrepos/github.com/${user}/${repository}
}

gitc ${1} ${2}
