#!/usr/bin/env zsh

source ${HOME}/.zshrc_func/800_myfuncs
source ${HOME}/.zshrc_func/100_logging

print "MEM `mem_used m`/`mem_total m`"
print "MEM `mem_used m`/`mem_total m`"

uptime | awk '{print $3}'|sed 's/,//'
