#!/usr/bin/env zsh

source ${HOME}/.zshrc_func/800_myfuncs
source ${HOME}/.zshrc_func/100_logging

isGitRepository() {
  [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1
  echo $?
}

gitBranchName() {
  git branch --contains=HEAD | cut -d ' ' -f 2 | cut -b 1-16 | grep -v '^$'
}

gitModifiedCount() {
  git status --short | grep -e ".M" | wc -l
}

gitNewFileCount(){
  git status --short | grep "A." | wc -l
}

gitUnstagedCount() {
  git status --short | grep "??" | wc -l
}

gitStashSize() {
  git stash list | wc -l
}

gitBranchSituation() {
  local situation=`git branch -v | grep \* | grep -E 'ahead|behind' | sed -r 's/[ *]\s(\S*).*\[((ahead|behind).+?)\].*/\2/g'`
  local aorb=`echo ${situation} | cut -d ' ' -f 1`
  local num=`echo ${situation} | cut -d ' ' -f 2`
  
  if [ -z ${aorb} ]
  then
    echo -n " "
    num=0
  elif [ ${aorb} = "ahead" ]
  then
    echo -n " "
  elif [ ${aorb} = "behind" ]
  then
    echo -n " "
  fi
  echo ${num}
}

gitRepositoryInfo() {
  if [ `isGitRepository` -eq 0 ]
  then
    echo " `gitBranchName` `gitBranchSituation`  `gitModifiedCount`  `gitNewFileCount`  `gitUnstagedCount`  `gitStashSize`"
  fi
}

gitRepositoryInfo
